### ISSUE TITLE
Add tag mappings

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#25]

**Comment by IohannesIohannium** [comment]
Since CK3 titles are rank-tiered, the mapping file should support the following fields:

- imp: The I:R tag
- ck3: The CK3 title
- rank: could be "e", "k" or "d", refers to the output rank of the country

For example `link = { imp = ROM ck3 = e_roman_empire rank = e }` would mean that a I:R Rome that would be converted to an Empire-rank country in CK3 would be mapped to e_roman_empire.

**Comment by IhateTrains** [comment]
I had the exact idea, we need to take rank in mind. I also think supporting multiple ranks should be done, for example I'd give a Roman state of kingdom rank `e_roman_empire` title: `link = { imp = ROM ck3 = e_roman_empire rank = e rank = k }`

**Comment by IohannesIohannium** [comment]
[tagMappings.txt](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/5545471/tagMappings.txt)
